### PR TITLE
Autonomous shuffleboard

### PR DESCRIPTION
**Pull request by varranvar**
Autonomous shuffleboard tab to configure the robot.

### CODE REVIEW

**Review by schineaj23 — CHANGES_REQUESTED** [review]
You should probably uncomment the code in RobotContainer.java for the Color Sensor before merging.
Other than that, looks good. I don't know if I'm allowed to actually approve pull requests though...

**Comment by jschoolcraft** [comment]
> You should probably uncomment the code in RobotContainer.java for the Color Sensor before merging.
> Other than that, looks good. I don't know if I'm allowed to actually approve pull requests though...

You're allowed to approve pull requests.  However if it's solely student reviewed I'd ask that @VasundharaGatne or @keiraSchoolcraft also review (2 reviews if all students).

**Review by jschoolcraft — CHANGES_REQUESTED** [review]
Let's discuss Saturday.

I'm not sure we should be adding `src/main/java/frc/robot/subsystems/AutonomousTab.java` to master. 

I think it's fine to put in a branch somewhere that we can use as an example, but I don't even think we've talked about our autonomous yet.

**Comment by varranvar** [comment]
> Let's discuss Saturday.
> 
> I'm not sure we should be adding `src/main/java/frc/robot/subsystems/AutonomousTab.java` to master.
> 
> I think it's fine to put in a branch somewhere that we can use as an example, but I don't even think we've talked about our autonomous yet.

Yeah I agree. We're not doing anything with autonomous right now so there's no need to clog up the build. However, I do think there should be a central class to store all the sensor and autonomous data.

**Pull request merged**
