### PR TITLE
Fixed Red & Yellow Color Sensor Confusion

### PR DESCRIPTION
**Pull request by schineaj23**
Also the shuffleboard config updated

### CODE REVIEW

**Review by jschoolcraft — COMMENTED** [review]
@schineaj23 at practice you mentioned changing two things:

- the color values
- just checking red if you know it's not blue/green

Do both of those need to be committed to work as you demonstrated in practice?

Have we compared the values we're setting for all the Color Target's based on observed values?

**Comment by schineaj23** [comment]
Q1: The code in this PR is what was demonstrated yesterday 2/20.
Q2: TL;DR yes
In `correctRed` I make sure that the color that is not green or blue, then get the raw red values of the detected (or observed) color, and compare them the green values of that color. Since red should not have as much green as yellow, I manually set the color to red and vice versa.

**Comment by jschoolcraft** [comment]
What I was asking was, is this raw sensor data from the color sensor when above the red target:

```java
private final Color RedTarget = ColorMatch.makeColor(0.75, 0.15, 0.0); // 0.561, 0.232, 0.144
```

I guess I'm asking if we're using what we think the color should be, or what REV or someone else thinks the color should be.  If, assuming we didn't have color values for RGBY and we needed to find them so we could match them later, we'd probably simulate field conditions, hold the sensor over the colors and record the raw readings from the sensor and use those for each color accordingly.

**Comment by schineaj23** [comment]
The commented values are what REV thinks the color should be, the current values are our own. We changed those values attempting solve R/Y the problem by making each color more saturated. Your solution is probably the best, and I can start working on that tomorrow, at a real comp the colors could be slightly varied

**Comment by jschoolcraft** [comment]
I’m just trying to understand the code.  We could probably keep a few sets
of those targets and comment all but the one we’re trying, e.g. one for
rev, one for us, etc

**Review by jschoolcraft — APPROVED** [review]

**Pull request merged**
