### PR TITLE
Shuffleboard Options and Calculating RPM of Control Panel

### PR DESCRIPTION
**Pull request by schineaj23**

### CODE REVIEW

**Review by jschoolcraft — CHANGES_REQUESTED** [review]
First, sorry this took 2 days for me to see.  In the future, if you're waiting on a review from me feel free to ping me in discord or mention it to me at practice.

Second, I think `ToggleStreamMode` and `ToggleCameraMode` should probably be instant commands.

What is in `isFinished()` certainly in `ToggleStreamMode` should all go in `execute()` and `isFinished()` just returns true.

I think the same is mostly true of `ToggleCameraMode`  I'm not sure why there's a `return false` at the end.  I think it'd be cleaner as:

- a default case on the switch statement
- a guard at the beginning of the function, e.g. `if (!stream) return false;` or something

In either case though, we're really just calling `setMode()` or `setStream()` and saying we're done.

**Comment by schineaj23** [comment]
Don't exactly know what the return value should be for corrupt data, as it will return 0 or 1, so decided to return 9 as a weird number.

**Review by jschoolcraft — COMMENTED** [review]
Why would we have weird/null values coming back?  Because we haven't initialized it yet?

I think we could just have sensible defaults, and if we're trying to toggle a mode (camera or stream) then we just choose a default that makes sense most of the time, e.g:

- camera in driver mode (not vision)
- stream limelight not secondary camera

then we could:

```java
public void execute() {
  switch(limelight.getStream()) {
    case Constants.StreamMode.PIP_MAIN:
      limelight.setStream(Constants.StreamMode.PIP_SECONDARY);
      break;
   default:
      limelight.setStream(Constants.StreamMode.PIP_MAIN);
      break;
  }
}
```

What do you think?

**Review by jschoolcraft — APPROVED** [review]
It's probably good to merge as it is, but consider my comment about sensible defaults  then we don't have to worry about magic numbers and can have a reasonable expectation that if we get weird errors we set the limelight to do what we probably want it to do.  And if we need to toggle again, so be it.

**Comment by schineaj23** [comment]
Ah, I interpreted the the guard as putting in the null checks. Will makes those changes before merging

**Pull request merged**
